######################################
# Set variables
######################################

###################
# yoltv5 input file variables
yoltv5_path: /
# object name variables (object names should be in order)
name_file_name: 'yoltv5_1class.name'
object_names:
- 'flower'

###################
# image slicing variables
data_root: ''
test_im_dir: ''
sliceHeight: 640
sliceWidth: 640
train_im_size: 640
slice_overlap: 0.1
im_ext: '.jpg'
out_ext: '.jpg'
# shouldn't need changed below here
skip_highly_overlapped_tiles: False
slice_verbose: False
n_threads_slice: 8
slice_sep: '__'
slice_overwrite: True
outdir_slice_root: ''
outdir_slice_ims: ''
outdir_slice_txt: ''
outpath_test_txt: ''
max_edge_aspect_ratio: 4

###################
# inference variables
outname_infer: 'yoltv5_1class'
weights_file: /out/BEST-YOLT.pt

###################
# post-process variables
detection_threshes:
- 0.2
n_plots: 8
allow_nested_detections: True
truth_file: '' # os.path.join(data_root, 'test', 'geojsons_geo', 'truth.geojson')
# seldom changed below here
extract_chips: False
chip_rescale_frac: 1.1
chip_ext: '.jpg'
edge_buffer_test: 1
max_bbox_size: 100
nms_overlap_thresh: 0.5